import {default as channels} from "./channels"
import {default as communications} from "./communications"
import {default as locations} from "./locations"
import {default as messages} from "./messages"
import {default as personas} from "./personas"
